# render.yaml — Git-aware deploys on Render

databases:
  - name: dmr-db
    plan: free
    region: oregon
    postgresMajorVersion: 16
    ipAllowList: []

services:
  # --- FastAPI backend ---
  - type: web
    name: doesmyresumematch-api
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r apps/api/requirements.txt
    startCommand: |
      cd apps/api && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dmr-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOW_ORIGINS
        # Allow your frontend origin (update if you add a custom domain)
        value: https://doesmyresumematch-web.onrender.com

  # --- Static Next.js frontend (uses Next.js 'export') ---
  - type: static_site
    name: doesmyresumematch-web
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://doesmyresumematch-api.onrender.com
      - key: BASE_PATH
        value: ""   # hosted at root on Render
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9 --activate
      pnpm install -w
      pnpm --filter web build
    publishPath: apps/web/out
    # SPA-friendly routing (keeps client-side routes working)
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
