services:
  # --- FastAPI backend ---
  - type: web
    name: doesmyresumematch-api
    env: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r apps/api/requirements.txt
    startCommand: |
      cd apps/api && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dmr-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOW_ORIGINS
        # Allow your frontend origin(s). Update with your custom domain later if you add one.
        value: https://doesmyresumematch-web.onrender.com

  # --- Postgres (pgvector if you use it) ---
  - type: postgres
    name: dmr-db
    plan: free
    ipAllowList: []

  # --- Static Next.js frontend (Next.js 'export') ---
  - type: static_site
    name: doesmyresumematch-web
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://doesmyresumematch-api.onrender.com
      - key: BASE_PATH
        value: ""    # empty because site is served at root on Render
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9 --activate
      pnpm install -w
      pnpm --filter web build
    publishPath: apps/web/out
    # Optional: SPA-style fallback if you use client-side routing
    routes:
      - type: redirect
        source: /_next/static/*
        destination: /_next/static/:splat
      - type: rewrite
        source: /*
        destination: /index.html

