# render.yaml — Git-aware deploys on Render (GitHub + Render only)

databases:
  - name: dmr-db
    region: oregon
    postgresMajorVersion: "17"
    ipAllowList: []

services:
  # --- FastAPI backend (Python web service) ---
  - type: web
    name: doesmyresumematch-api
    runtime: python         # (prefer 'runtime' over legacy 'env')
    region: oregon
    rootDir: apps/api       # monorepo: watch only this folder for this service
    buildCommand: |
      pip install -r requirements.txt
    # Run DB migrations just before the app starts
    preDeployCommand: |
      alembic upgrade head
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dmr-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOW_ORIGINS
        # allow your frontend origin (update if you add a custom domain)
        value: https://doesmyresumematch-web.onrender.com

  # --- Next.js frontend (Static Site) ---
  - type: web
    name: doesmyresumematch-web
    runtime: static         # ✅ static site
    # Monorepo build: install at workspace root, then build the web app
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9 --activate
      pnpm install -w
      pnpm --filter web build
    staticPublishPath: ./apps/web/out   # ✅ correct field name for static sites
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://doesmyresumematch-api.onrender.com
      - key: BASE_PATH
        value: ""    # site served at root on Render
    # SPA-friendly routing for App Router / client routes
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
