name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install -w
      
      - name: Prepare Playwright cache
        run: mkdir -p ~/.cache/ms-playwright
      
      - name: Restore Playwright cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      # ✅ Key fix: install browsers + OS deps
      - name: Install Playwright (browsers + deps)
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      # Prefer Makefile if present, else smart fallback
      - name: Run tests
        run: |
          if [ -f Makefile ] && grep -q "^test:" Makefile; then
            make test
          elif jq -e '.scripts["test:e2e"]' apps/web/package.json >/dev/null 2>&1; then
            pnpm --filter web test:e2e
          elif jq -e '.scripts.playwright' apps/web/package.json >/dev/null 2>&1; then
            pnpm --filter web playwright test
          else
            pnpm -w test
          fi

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/playwright-report
          if-no-files-found: ignore
